/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as HubRouteImport } from './routes/hub'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RelatoriosVendasRouteImport } from './routes/relatorios.vendas'
import { Route as RelatoriosFluxoCaixaRouteImport } from './routes/relatorios.fluxo-caixa'
import { Route as RelatoriosFiscalRouteImport } from './routes/relatorios.fiscal'
import { Route as RelatoriosFinanceiroRouteImport } from './routes/relatorios.financeiro'
import { Route as RelatoriosEstoqueRouteImport } from './routes/relatorios.estoque'
import { Route as RelatoriosDreRouteImport } from './routes/relatorios.dre'
import { Route as RelatoriosContasReceberRouteImport } from './routes/relatorios.contas-receber'
import { Route as RelatoriosComprasRouteImport } from './routes/relatorios.compras'
import { Route as RelatoriosCaixaRouteImport } from './routes/relatorios.caixa'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminModosRouteImport } from './routes/admin.modos'
import { Route as AdminEstatisticasRouteImport } from './routes/admin.estatisticas'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfigComercialRouteImport } from './routes/admin.config-comercial'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RelatoriosVendasRoute = RelatoriosVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosFluxoCaixaRoute = RelatoriosFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosFiscalRoute = RelatoriosFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosFinanceiroRoute = RelatoriosFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosEstoqueRoute = RelatoriosEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosDreRoute = RelatoriosDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosContasReceberRoute = RelatoriosContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosComprasRoute = RelatoriosComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => RelatoriosRoute,
} as any)
const RelatoriosCaixaRoute = RelatoriosCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => RelatoriosRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModosRoute = AdminModosRouteImport.update({
  id: '/modos',
  path: '/modos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstatisticasRoute = AdminEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigComercialRoute = AdminConfigComercialRouteImport.update({
  id: '/config-comercial',
  path: '/config-comercial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/hub': typeof HubRoute
  '/modulos': typeof ModulosRoute
  '/pdv': typeof PdvRoute
  '/planos': typeof PlanosRoute
  '/pos': typeof PosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/vendas': typeof VendasRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/config-comercial': typeof AdminConfigComercialRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/modos': typeof AdminModosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/relatorios/caixa': typeof RelatoriosCaixaRoute
  '/relatorios/compras': typeof RelatoriosComprasRoute
  '/relatorios/contas-receber': typeof RelatoriosContasReceberRoute
  '/relatorios/dre': typeof RelatoriosDreRoute
  '/relatorios/estoque': typeof RelatoriosEstoqueRoute
  '/relatorios/financeiro': typeof RelatoriosFinanceiroRoute
  '/relatorios/fiscal': typeof RelatoriosFiscalRoute
  '/relatorios/fluxo-caixa': typeof RelatoriosFluxoCaixaRoute
  '/relatorios/vendas': typeof RelatoriosVendasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/hub': typeof HubRoute
  '/modulos': typeof ModulosRoute
  '/pdv': typeof PdvRoute
  '/planos': typeof PlanosRoute
  '/pos': typeof PosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/vendas': typeof VendasRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/config-comercial': typeof AdminConfigComercialRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/modos': typeof AdminModosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/relatorios/caixa': typeof RelatoriosCaixaRoute
  '/relatorios/compras': typeof RelatoriosComprasRoute
  '/relatorios/contas-receber': typeof RelatoriosContasReceberRoute
  '/relatorios/dre': typeof RelatoriosDreRoute
  '/relatorios/estoque': typeof RelatoriosEstoqueRoute
  '/relatorios/financeiro': typeof RelatoriosFinanceiroRoute
  '/relatorios/fiscal': typeof RelatoriosFiscalRoute
  '/relatorios/fluxo-caixa': typeof RelatoriosFluxoCaixaRoute
  '/relatorios/vendas': typeof RelatoriosVendasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/hub': typeof HubRoute
  '/modulos': typeof ModulosRoute
  '/pdv': typeof PdvRoute
  '/planos': typeof PlanosRoute
  '/pos': typeof PosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRouteWithChildren
  '/vendas': typeof VendasRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/config-comercial': typeof AdminConfigComercialRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/modos': typeof AdminModosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/relatorios/caixa': typeof RelatoriosCaixaRoute
  '/relatorios/compras': typeof RelatoriosComprasRoute
  '/relatorios/contas-receber': typeof RelatoriosContasReceberRoute
  '/relatorios/dre': typeof RelatoriosDreRoute
  '/relatorios/estoque': typeof RelatoriosEstoqueRoute
  '/relatorios/financeiro': typeof RelatoriosFinanceiroRoute
  '/relatorios/fiscal': typeof RelatoriosFiscalRoute
  '/relatorios/fluxo-caixa': typeof RelatoriosFluxoCaixaRoute
  '/relatorios/vendas': typeof RelatoriosVendasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/hub'
    | '/modulos'
    | '/pdv'
    | '/planos'
    | '/pos'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/config-comercial'
    | '/admin/empresas'
    | '/admin/estatisticas'
    | '/admin/modos'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/relatorios/caixa'
    | '/relatorios/compras'
    | '/relatorios/contas-receber'
    | '/relatorios/dre'
    | '/relatorios/estoque'
    | '/relatorios/financeiro'
    | '/relatorios/fiscal'
    | '/relatorios/fluxo-caixa'
    | '/relatorios/vendas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/hub'
    | '/modulos'
    | '/pdv'
    | '/planos'
    | '/pos'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/config-comercial'
    | '/admin/empresas'
    | '/admin/estatisticas'
    | '/admin/modos'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/relatorios/caixa'
    | '/relatorios/compras'
    | '/relatorios/contas-receber'
    | '/relatorios/dre'
    | '/relatorios/estoque'
    | '/relatorios/financeiro'
    | '/relatorios/fiscal'
    | '/relatorios/fluxo-caixa'
    | '/relatorios/vendas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/caixa'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/hub'
    | '/modulos'
    | '/pdv'
    | '/planos'
    | '/pos'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/config-comercial'
    | '/admin/empresas'
    | '/admin/estatisticas'
    | '/admin/modos'
    | '/admin/modulos'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/relatorios/caixa'
    | '/relatorios/compras'
    | '/relatorios/contas-receber'
    | '/relatorios/dre'
    | '/relatorios/estoque'
    | '/relatorios/financeiro'
    | '/relatorios/fiscal'
    | '/relatorios/fluxo-caixa'
    | '/relatorios/vendas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CaixaRoute: typeof CaixaRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FornecedoresRoute: typeof FornecedoresRoute
  HubRoute: typeof HubRoute
  ModulosRoute: typeof ModulosRoute
  PdvRoute: typeof PdvRoute
  PlanosRoute: typeof PlanosRoute
  PosRoute: typeof PosRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRouteWithChildren
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/relatorios/vendas': {
      id: '/relatorios/vendas'
      path: '/vendas'
      fullPath: '/relatorios/vendas'
      preLoaderRoute: typeof RelatoriosVendasRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/fluxo-caixa': {
      id: '/relatorios/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/relatorios/fluxo-caixa'
      preLoaderRoute: typeof RelatoriosFluxoCaixaRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/fiscal': {
      id: '/relatorios/fiscal'
      path: '/fiscal'
      fullPath: '/relatorios/fiscal'
      preLoaderRoute: typeof RelatoriosFiscalRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/financeiro': {
      id: '/relatorios/financeiro'
      path: '/financeiro'
      fullPath: '/relatorios/financeiro'
      preLoaderRoute: typeof RelatoriosFinanceiroRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/estoque': {
      id: '/relatorios/estoque'
      path: '/estoque'
      fullPath: '/relatorios/estoque'
      preLoaderRoute: typeof RelatoriosEstoqueRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/dre': {
      id: '/relatorios/dre'
      path: '/dre'
      fullPath: '/relatorios/dre'
      preLoaderRoute: typeof RelatoriosDreRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/contas-receber': {
      id: '/relatorios/contas-receber'
      path: '/contas-receber'
      fullPath: '/relatorios/contas-receber'
      preLoaderRoute: typeof RelatoriosContasReceberRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/compras': {
      id: '/relatorios/compras'
      path: '/compras'
      fullPath: '/relatorios/compras'
      preLoaderRoute: typeof RelatoriosComprasRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/relatorios/caixa': {
      id: '/relatorios/caixa'
      path: '/caixa'
      fullPath: '/relatorios/caixa'
      preLoaderRoute: typeof RelatoriosCaixaRouteImport
      parentRoute: typeof RelatoriosRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modos': {
      id: '/admin/modos'
      path: '/modos'
      fullPath: '/admin/modos'
      preLoaderRoute: typeof AdminModosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estatisticas': {
      id: '/admin/estatisticas'
      path: '/estatisticas'
      fullPath: '/admin/estatisticas'
      preLoaderRoute: typeof AdminEstatisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config-comercial': {
      id: '/admin/config-comercial'
      path: '/config-comercial'
      fullPath: '/admin/config-comercial'
      preLoaderRoute: typeof AdminConfigComercialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfigComercialRoute: typeof AdminConfigComercialRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminEstatisticasRoute: typeof AdminEstatisticasRoute
  AdminModosRoute: typeof AdminModosRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfigComercialRoute: AdminConfigComercialRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminEstatisticasRoute: AdminEstatisticasRoute,
  AdminModosRoute: AdminModosRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RelatoriosRouteChildren {
  RelatoriosCaixaRoute: typeof RelatoriosCaixaRoute
  RelatoriosComprasRoute: typeof RelatoriosComprasRoute
  RelatoriosContasReceberRoute: typeof RelatoriosContasReceberRoute
  RelatoriosDreRoute: typeof RelatoriosDreRoute
  RelatoriosEstoqueRoute: typeof RelatoriosEstoqueRoute
  RelatoriosFinanceiroRoute: typeof RelatoriosFinanceiroRoute
  RelatoriosFiscalRoute: typeof RelatoriosFiscalRoute
  RelatoriosFluxoCaixaRoute: typeof RelatoriosFluxoCaixaRoute
  RelatoriosVendasRoute: typeof RelatoriosVendasRoute
}

const RelatoriosRouteChildren: RelatoriosRouteChildren = {
  RelatoriosCaixaRoute: RelatoriosCaixaRoute,
  RelatoriosComprasRoute: RelatoriosComprasRoute,
  RelatoriosContasReceberRoute: RelatoriosContasReceberRoute,
  RelatoriosDreRoute: RelatoriosDreRoute,
  RelatoriosEstoqueRoute: RelatoriosEstoqueRoute,
  RelatoriosFinanceiroRoute: RelatoriosFinanceiroRoute,
  RelatoriosFiscalRoute: RelatoriosFiscalRoute,
  RelatoriosFluxoCaixaRoute: RelatoriosFluxoCaixaRoute,
  RelatoriosVendasRoute: RelatoriosVendasRoute,
}

const RelatoriosRouteWithChildren = RelatoriosRoute._addFileChildren(
  RelatoriosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CaixaRoute: CaixaRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  FornecedoresRoute: FornecedoresRoute,
  HubRoute: HubRoute,
  ModulosRoute: ModulosRoute,
  PdvRoute: PdvRoute,
  PlanosRoute: PlanosRoute,
  PosRoute: PosRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRouteWithChildren,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
